# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'NovedosaApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Fix 'folly/coro/Coroutine.h' file not found (Xcode 26+ compatibility)
    # Patch both RCT-Folly and ReactNativeDependencies
    ["Pods/RCT-Folly", "Pods/ReactNativeDependencies"].each do |path|
      if Dir.exist?(path)
        system("chmod -R u+w #{path}")
        Dir.glob("#{path}/folly/Portability.h").each do |file|
          text = File.read(file)
          new_contents = text.gsub('#define FOLLY_HAS_COROUTINES 1', '#define FOLLY_HAS_COROUTINES 0')
          File.open(file, "w") { |f| f.puts new_contents }
        end
      end
    end
  end
end
